version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3010:3001
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432/postgres

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
